update_fastlane

fastlane_version "2.68.0"

default_platform :ios

platform :ios do
  
  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_status_clean
    increment_build_number(build_number: latest_testflight_build_number + 1)
    commit_version_bump
    push_to_git_remote

    build_app
    
    upload_to_testflight
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    capture_screenshots
    build_app
    upload_to_app_store(force: true)
  end
end
